"""PostgreSQL adapter for the application's small, shared SQL interface.

All application writes take one transaction-scoped advisory lock. This preserves
SQLite's serialized check-and-write behavior across multiple app processes.
"""
import re
from functools import lru_cache

import psycopg
from psycopg_pool import ConnectionPool

IDENTITIES = {
    'doctors': 'doctor_id', 'wards': 'ward_id', 'events': 'event_id',
    'decisions': 'decision_id', 'staff_users': 'user_id', 'staff_audit': 'audit_id',
    'doctor_breaks': 'break_id', 'consultations': 'consultation_id', 'vitals': 'vital_id',
}
TIMESTAMP = "to_char(CURRENT_TIMESTAMP AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS.US')"
TOKENS = re.compile(r"'(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|--[^\n]*|/\*.*?\*/|\?", re.S)


class Row(dict):
    """Support both column-name and positional access, like sqlite3.Row."""
    def __getitem__(self, key):
        return tuple(self.values())[key] if isinstance(key, int) else super().__getitem__(key)


def row_factory(cursor):
    names = [c.name for c in cursor.description] if cursor.description else []
    return lambda values: Row(zip(names, values))


@lru_cache(maxsize=4)
def pool(url):
    return ConnectionPool(url, min_size=0, max_size=5, timeout=20,
                          kwargs={'row_factory': row_factory, 'connect_timeout': 10},
                          # Never emit a connection URL from this module.
                          name='medagent', open=True)


def placeholders(query, *, numbered=False):
    count = 0
    def replace(match):
        nonlocal count
        if match.group() != '?':
            return match.group()
        count += 1
        return f'${count}' if numbered else '%s'
    return TOKENS.sub(replace, query)


def translate(query):
    """Translate only the dialect features used by MedAgent's trusted code."""
    pragma = re.fullmatch(r'\s*PRAGMA table_info\((\w+)\)\s*', query, re.I)
    if pragma:
        # Table names here come from schema initialization, not request values.
        return ("SELECT column_name AS name FROM information_schema.columns "
                "WHERE table_schema='public' AND table_name='" + pragma[1] + "' ORDER BY ordinal_position")
    if query == "SELECT 1 FROM sqlite_master WHERE name='appointments'":
        return "SELECT 1 FROM information_schema.tables WHERE table_schema='public' AND table_name='appointments'"
    create = re.match(r'\s*CREATE TABLE IF NOT EXISTS (\w+)', query, re.I)
    if create:
        table = create[1].lower()
        if table in IDENTITIES:
            start = ' (START WITH 10)' if table == 'doctors' else ''
            query = re.sub(r'INTEGER PRIMARY KEY(?: AUTOINCREMENT)?',
                           'INTEGER GENERATED BY DEFAULT AS IDENTITY' + start + ' PRIMARY KEY', query, count=1)
        if table in ('appointments', 'visits'):
            # SQLite exposes insertion order as rowid. Keep queue tie-breaking
            # stable on PostgreSQL too, including rows created in the same second.
            pos = query.rfind(')')
            query = query[:pos] + ', rowid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE' + query[pos:]
        query = re.sub(r'\bREAL\b', 'DOUBLE PRECISION', query)
    query = query.replace('CURRENT_TIMESTAMP', TIMESTAMP)
    if re.match(r'\s*INSERT OR IGNORE', query, re.I):
        query = re.sub(r'INSERT OR IGNORE', 'INSERT', query, count=1, flags=re.I).rstrip().rstrip(';')
        query += ' ON CONFLICT DO NOTHING'
    return query


class Cursor:
    def __init__(self, cursor, lastrowid=None):
        self.cursor = cursor
        self.lastrowid = lastrowid

    @property
    def rowcount(self): return self.cursor.rowcount
    def fetchone(self): return self.cursor.fetchone()
    def fetchall(self): return self.cursor.fetchall()
    def __iter__(self): return iter(self.cursor)


class Connection:
    def __init__(self, conn): self.raw = conn

    def execute(self, query, params=()):
        query = translate(query)
        insert = re.match(r'\s*INSERT INTO (\w+)', query, re.I)
        identity = IDENTITIES.get(insert[1].lower()) if insert else None
        if identity and 'RETURNING' not in query.upper():
            query = query.rstrip().rstrip(';') + ' RETURNING ' + identity
        else:
            identity = None
        if params:
            query = placeholders(query.replace('%', '%%'))
        result = self.raw.execute(query, params or None)
        inserted = result.fetchone() if identity else None
        return Cursor(result, inserted[0] if inserted else None)


def authorize_read(query, allowed):
    """Accept a narrow SELECT grammar, never arbitrary PostgreSQL statements.

    The application owns all table definitions. In addition to read-only
    transactions, reject hidden tables, functions with side effects, casts,
    SELECT INTO, locking clauses, CTEs and multiple statements before execution.
    """
    import json
    from pglast import parser
    from .auth import AccessDenied
    nodes = {'SelectStmt', 'ResTarget', 'ColumnRef', 'String', 'Integer', 'Float',
             'Boolean', 'A_Star', 'RangeVar', 'JoinExpr', 'A_Expr', 'A_Const',
             'ParamRef', 'SortBy', 'BoolExpr', 'NullTest', 'BooleanTest',
             'FuncCall', 'CoalesceExpr', 'CaseExpr', 'CaseWhen', 'SubLink',
             'RangeSubselect', 'Alias', 'List'}
    functions = {'count', 'sum', 'avg', 'min', 'max', 'round', 'abs',
                 'lower', 'upper', 'length', 'trim', 'btrim', 'substr'}
    def deny():
        raise AccessDenied('This data request is not permitted for your role.')
    def walk(value):
        if isinstance(value, list):
            for item in value: walk(item)
        elif isinstance(value, dict):
            for key, item in value.items():
                if key[:1].isupper() and key not in nodes:
                    deny()
                if key == 'SelectStmt' and any(item.get(k) for k in ('intoClause', 'lockingClause', 'withClause')):
                    deny()
                if key == 'RangeVar' and (item.get('catalogname') or item.get('schemaname') or item.get('relname') not in allowed):
                    deny()
                if key == 'FuncCall':
                    names = item.get('funcname', [])
                    if len(names) != 1 or names[0].get('String', {}).get('sval') not in functions:
                        deny()
                if key == 'A_Expr':
                    names = item.get('name', [])
                    if len(names) != 1 or names[0].get('String', {}).get('sval') not in {'=', '<>', '!=', '<', '>', '<=', '>=', '+', '-', '*', '/', '~~', '!~~', '~~*', '!~~*'}:
                        deny()
                walk(item)
    try:
        statements = json.loads(parser.parse_sql_json(placeholders(query, numbered=True)))['stmts']
        if len(statements) != 1 or set(statements[0]['stmt']) != {'SelectStmt'}:
            deny()
        walk(statements[0]['stmt'])
    except (ValueError, KeyError, parser.ParseError) as exc:
        raise AccessDenied('This data request is not permitted for your role.') from exc
